@startuml clases

class Tablero {
    + filas: int
    + columnas: int
    + minas: int
    + casillas: Array[Array[Casilla]]
    + constructor(filas: int, columnas: int, minas: int)
    + crearTablero()
}

abstract class Casilla {
    # coordenadaY: int
    # coordenadaX: int
    # marcada: boolean
    +{abstract} constructor(coordenadaY: int, coordenadaX: int)
    + marcar()
    + desmarcar()
}

class CasillaNormal {
    - minasAlrededor: Int
    + calcularMinasAlrededor(): Array[Casilla]
}

class CasillaMina {
    + perder()
}



Tablero *-- Casilla
Casilla <|-- CasillaMina
Casilla <|-- CasillaNormal
@enduml